# Generated by Django 2.2.24 on 2023-08-23 15:24

from django.db import migrations
import phonenumbers


def change_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats:
        owners_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(owners_phonenumber):
            flat.owner_pure_phone = owners_phonenumber
            flat.save()


def move_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(change_numbers, move_backward),
    ]
