# Generated by Django 2.2.24 on 2023-08-25 06:42

from django.db import migrations


def copy_flat_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    Owner = apps.get_model('property', 'Owner')

    for flat in flats.iterator():
    
        Owner.objects.get_or_create(
            owner=flat.owner, 
            owners_phonenumber=flat.owners_phonenumber, 
            owner_pure_phone=flat.owner_pure_phone
        )
    

def move_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(copy_flat_to_owners, move_backward),
    ]
