# Generated by Django 2.2.24 on 2023-08-25 08:08

from django.db import migrations


def copy_flat_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flats = Flat.objects.all()

    for flat in flats.iterator():
    
        owner, _ = Owner.objects.get_or_create(owner=flat.owner, owner_pure_phone=flat.owner_pure_phone)
        owner.flat.add(flat)
    

def move_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230825_0942'),
    ]

    operations = [
        migrations.RunPython(copy_flat_to_owners, move_backward),
    ]
